---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
spec:
  secretName: ingress-certificate
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt
    group: cert-manager.io
  dnsNames:
    - "*.demo.meisenzahl.org"